Updated to be able to use latest distil version. It means that ingest has to be built in the container for gdal support.

diff --git a/server/Dockerfile b/server/Dockerfile
--- a/server/Dockerfile
+++ b/server/Dockerfile
@@ -1,5 +1,5 @@
 # Set the base image to postgres alpine
-FROM postgres:10-alpine
+FROM postgres:13-alpine
 
 # Update postgres to use a new data folder.
 RUN mkdir -p /usr/local/pgsql/data
@@ -8,6 +8,7 @@ RUN chmod 700 /usr/local/pgsql/data
 
 ENV PGDATA="/usr/local/pgsql/data"
 
+ADD docker-entrypoint.sh /
 ADD postgres-init.sh /
 ADD init.sql /docker-entrypoint-initdb.d/
 RUN /postgres-init.sh -p 5432:5432 -d postgres
@@ -17,19 +18,45 @@ RUN apk update
 
 # missing from baseline alpine
 RUN apk add --no-cache ca-certificates
+RUN apk update && apk add bash git make build-base
+RUN apk add gdal gdal-dev
+
+ARG DISTIL_BRANCH
+RUN apk add --no-cache git make musl-dev go
+ENV GOPROXY=direct
+ENV GO111MODULE=on
+
+RUN set -eux; \
+        \
+        apk add --no-cache --virtual .gosu-deps \
+                ca-certificates \
+                dpkg \
+                gnupg \
+        ; \
+        \
+        dpkgArch="$(dpkg --print-architecture | awk -F- '{ print $NF }')"; \
+        wget -O /usr/local/bin/gosu "https://github.com/tianon/gosu/releases/download/1.12/gosu-$dpkgArch"; \
+        wget -O /usr/local/bin/gosu.asc "https://github.com/tianon/gosu/releases/download/1.12/gosu-$dpkgArch.asc"; \
+        \
+# verify the signature
+        export GNUPGHOME="$(mktemp -d)"; \
+        gpg --batch --keyserver hkps://keys.openpgp.org --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4; \
+        gpg --batch --verify /usr/local/bin/gosu.asc /usr/local/bin/gosu; \
+        command -v gpgconf && gpgconf --kill all || :; \
+        rm -rf "$GNUPGHOME" /usr/local/bin/gosu.asc; \
+        \
+# clean up fetch dependencies
+        apk del --no-network .gosu-deps; \
+        \
+        chmod +x /usr/local/bin/gosu;
 
 # copy in distil-ingest
 RUN mkdir -p /distil-ingest
 WORKDIR /distil-ingest
 ADD config.sh .
-ADD distil-ingest .
-ADD distil-merge .
-ADD distil-rank .
-ADD distil-classify .
-ADD distil-summary .
-ADD distil-featurize .
-ADD distil-cluster .
 ADD ingest.sh .
+RUN env GOOS=linux GOARCH=amd64 go get -a -v github.com/uncharted-distil/distil-ingest/cmd/distil-ingest@$DISTIL_BRANCH
+RUN cp ~/go/bin/distil-ingest ./distil-ingest
 
 # copy in d3m test data
 RUN mkdir -p /input
@@ -37,11 +64,9 @@ COPY data /input
 
 # start postgres and run ingest
 ADD https://raw.githubusercontent.com/vishnubob/wait-for-it/e1f115e4ca285c3c24e847c4dd4be955e0ed51c2/wait-for-it.sh /
+RUN chmod 777 /wait-for-it.sh
 RUN /docker-entrypoint.sh postgres & \
-  /bin/bash /wait-for-it.sh -t 0 localhost:5432 -- psql -U postgres -f /docker-entrypoint-initdb.d/init.sql; \
-  sleep 60; \
-  /distil-ingest/ingest.sh; \
-  exit 0;
+  sleep 60; /distil-ingest/ingest.sh
 
 # remove ingest related files
 WORKDIR /
